Name:           ros-hydro-collada-urdf
Version:        1.10.20
Release:        0%{?dist}
Summary:        ROS collada_urdf package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/collada_urdf
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       collada-dom-devel
Requires:       ros-hydro-angles
Requires:       ros-hydro-collada-parser
Requires:       ros-hydro-geometric-shapes
Requires:       ros-hydro-resource-retriever
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-tf
Requires:       ros-hydro-urdf
Requires:       ros-hydro-urdfdom
Requires:       ros-hydro-urdfdom-headers
BuildRequires:  assimp
BuildRequires:  collada-dom-devel
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin >= 0.5.68
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-collada-parser
BuildRequires:  ros-hydro-geometric-shapes
BuildRequires:  ros-hydro-resource-retriever
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-urdf
BuildRequires:  ros-hydro-urdfdom
BuildRequires:  ros-hydro-urdfdom-headers

%description
This package contains a tool to convert Unified Robot Description Format (URDF)
documents into COLLAborative Design Activity (COLLADA) documents. Implements
robot-specific COLLADA extensions as defined by
http://openrave.programmingvision.com/index.php/Started:COLLADA

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Aug 01 2014 Ioan Sucan <isucan@gmail.com> - 1.10.20-0
- Autogenerated by Bloom

